function A = A_ballerina(in1,in2)
%A_ballerina
%    A = A_ballerina(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    19-Nov-2024 14:34:00

I1 = in2(5,:);
I2 = in2(6,:);
I3 = in2(7,:);
I4 = in2(8,:);
I5 = in2(9,:);
Ir = in2(10,:);
N = in2(11,:);
l_AC = in2(18,:);
l_A_m3 = in2(14,:);
l_B_m2 = in2(13,:);
l_C_m4 = in2(15,:);
l_OA = in2(16,:);
l_OB = in2(17,:);
l_O_m1 = in2(12,:);
m1 = in2(1,:);
m2 = in2(2,:);
m3 = in2(3,:);
m4 = in2(4,:);
th2 = in1(2,:);
t2 = cos(th2);
t3 = N.^2;
t4 = l_AC.^2;
t5 = l_A_m3.^2;
t6 = l_B_m2.^2;
t7 = l_C_m4.^2;
t8 = l_OA.^2;
t9 = l_OB.^2;
t10 = l_O_m1.^2;
t11 = Ir.*N;
t21 = l_C_m4.*l_OA.*m4.*2.0;
t12 = Ir.*t3;
t13 = m4.*t4;
t14 = m3.*t5;
t15 = m2.*t6;
t16 = m4.*t7;
t17 = m3.*t8;
t18 = m2.*t9;
t19 = m4.*t8;
t20 = m1.*t10;
t22 = l_AC.*l_C_m4.*m4.*t2;
t23 = l_AC.*l_OA.*m4.*t2;
t24 = l_A_m3.*l_OA.*m3.*t2;
t25 = l_B_m2.*l_OB.*m2.*t2;
t26 = t22.*2.0;
t27 = t23.*2.0;
t28 = t24.*2.0;
t29 = t25.*2.0;
t30 = I2+I3+t11+t13+t14+t15+t22+t23+t24+t25;
t31 = I1+I2+I3+I4+Ir+t11+t13+t14+t15+t16+t17+t18+t19+t20+t21+t26+t27+t28+t29;
A = reshape([I1+I2+I3+I4+Ir+t12+t13+t14+t15+t16+t17+t18+t19+t20+t21+t26+t27+t28+t29,t30,t31,t30,I2+I3+t12+t13+t14+t15,t30,t31,t30,I1+I2+I3+I4+I5+Ir.*2.0+t12+t13+t14+t15+t16+t17+t18+t19+t20+t21+t26+t27+t28+t29],[3,3]);
end
