function b = b_ballerina(in1,in2,in3)
%B_BALLERINA
%    B = B_BALLERINA(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    19-Nov-2024 14:34:01

dth1 = in1(4,:);
dth2 = in1(5,:);
dth3 = in1(6,:);
l_AC = in3(18,:);
l_A_m3 = in3(14,:);
l_B_m2 = in3(13,:);
l_C_m4 = in3(15,:);
l_OA = in3(16,:);
l_OB = in3(17,:);
m2 = in3(2,:);
m3 = in3(3,:);
m4 = in3(4,:);
tau1 = in2(1,:);
tau2 = in2(2,:);
tau3 = in2(3,:);
th2 = in1(2,:);
t2 = sin(th2);
t3 = dth1.^2;
t4 = dth3.^2;
t5 = dth2.*l_AC.*l_C_m4.*m4.*t2;
t6 = dth2.*l_AC.*l_OA.*m4.*t2;
t7 = dth2.*l_A_m3.*l_OA.*m3.*t2;
t8 = dth2.*l_B_m2.*l_OB.*m2.*t2;
t9 = dth1.*l_AC.*l_C_m4.*m4.*t2.*2.0;
t10 = dth3.*l_AC.*l_C_m4.*m4.*t2.*2.0;
t11 = dth1.*l_AC.*l_OA.*m4.*t2.*2.0;
t12 = dth3.*l_AC.*l_OA.*m4.*t2.*2.0;
t13 = dth1.*l_A_m3.*l_OA.*m3.*t2.*2.0;
t14 = dth3.*l_A_m3.*l_OA.*m3.*t2.*2.0;
t15 = dth1.*l_B_m2.*l_OB.*m2.*t2.*2.0;
t16 = dth3.*l_B_m2.*l_OB.*m2.*t2.*2.0;
t17 = t5+t6+t7+t8+t9+t10+t11+t12+t13+t14+t15+t16;
t18 = dth2.*t17;
b = [t18+tau1;tau2+dth2.*(dth1.*l_AC.*l_C_m4.*m4.*t2+dth3.*l_AC.*l_C_m4.*m4.*t2+dth1.*l_AC.*l_OA.*m4.*t2+dth3.*l_AC.*l_OA.*m4.*t2+dth1.*l_A_m3.*l_OA.*m3.*t2+dth3.*l_A_m3.*l_OA.*m3.*t2+dth1.*l_B_m2.*l_OB.*m2.*t2+dth3.*l_B_m2.*l_OB.*m2.*t2)-dth1.*t5-dth1.*t6-dth1.*t7-dth3.*t5-dth1.*t8-dth3.*t6-dth3.*t7-dth3.*t8-l_AC.*l_C_m4.*m4.*t2.*t3-l_AC.*l_C_m4.*m4.*t2.*t4-l_AC.*l_OA.*m4.*t2.*t3-l_AC.*l_OA.*m4.*t2.*t4-l_A_m3.*l_OA.*m3.*t2.*t3-l_A_m3.*l_OA.*m3.*t2.*t4-l_B_m2.*l_OB.*m2.*t2.*t3-l_B_m2.*l_OB.*m2.*t2.*t4-dth1.*dth3.*l_AC.*l_C_m4.*m4.*t2.*2.0-dth1.*dth3.*l_AC.*l_OA.*m4.*t2.*2.0-dth1.*dth3.*l_A_m3.*l_OA.*m3.*t2.*2.0-dth1.*dth3.*l_B_m2.*l_OB.*m2.*t2.*2.0;t18+tau3];
end
