function Corr_Joint_Sp = Corr_leg(in1,in2)
%Corr_leg
%    Corr_Joint_Sp = Corr_leg(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    19-Nov-2024 14:34:01

dth1 = in1(4,:);
dth2 = in1(5,:);
dth3 = in1(6,:);
l_AC = in2(18,:);
l_A_m3 = in2(14,:);
l_B_m2 = in2(13,:);
l_C_m4 = in2(15,:);
l_OA = in2(16,:);
l_OB = in2(17,:);
m2 = in2(2,:);
m3 = in2(3,:);
m4 = in2(4,:);
th2 = in1(2,:);
t2 = sin(th2);
t3 = dth1.*2.0;
t4 = dth3.*2.0;
t5 = l_AC.*l_C_m4.*m4;
t6 = l_AC.*l_OA.*m4;
t7 = l_A_m3.*l_OA.*m3;
t8 = l_B_m2.*l_OB.*m2;
t9 = dth2+t3+t4;
t10 = t5+t6+t7+t8;
t11 = dth2.*t2.*t9.*t10;
t12 = -t11;
Corr_Joint_Sp = [t12;t2.*t10.*(dth1+dth3).^2;t12];
end
