function E = energy_ballerina(in1,in2)
%ENERGY_BALLERINA
%    E = ENERGY_BALLERINA(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    14-Nov-2024 14:47:42

I1 = in2(5,:);
I2 = in2(6,:);
I3 = in2(7,:);
I4 = in2(8,:);
I5 = in2(9,:);
Ir = in2(10,:);
N = in2(11,:);
dth1 = in1(4,:);
dth2 = in1(5,:);
dth3 = in1(6,:);
l_AC = in2(18,:);
l_A_m3 = in2(14,:);
l_B_m2 = in2(13,:);
l_C_m4 = in2(15,:);
l_OA = in2(16,:);
l_OB = in2(17,:);
l_O_m1 = in2(12,:);
m1 = in2(1,:);
m2 = in2(2,:);
m3 = in2(3,:);
m4 = in2(4,:);
th2 = in1(2,:);
t2 = cos(th2);
t3 = N.^2;
t4 = dth1.^2;
t5 = dth2.^2;
t6 = dth3.^2;
t7 = l_AC.^2;
t8 = l_A_m3.^2;
t9 = l_B_m2.^2;
t10 = l_C_m4.^2;
t11 = l_OA.^2;
t12 = l_OB.^2;
t13 = l_O_m1.^2;
et1 = (I1.*t4)./2.0+(I2.*t4)./2.0+(I1.*t6)./2.0+(I2.*t5)./2.0+(I3.*t4)./2.0+(I2.*t6)./2.0+(I3.*t5)./2.0+(I4.*t4)./2.0+(I3.*t6)./2.0+(I4.*t6)./2.0+(I5.*t6)./2.0+(Ir.*t4)./2.0+Ir.*t6+I1.*dth1.*dth3+I2.*dth1.*dth2+I2.*dth1.*dth3+I3.*dth1.*dth2+I2.*dth2.*dth3+I3.*dth1.*dth3+I3.*dth2.*dth3+I4.*dth1.*dth3+Ir.*dth1.*dth3+(Ir.*t3.*t4)./2.0+(Ir.*t3.*t5)./2.0+(Ir.*t3.*t6)./2.0+(m2.*t4.*t9)./2.0+(m3.*t4.*t8)./2.0+(m4.*t4.*t7)./2.0+(m2.*t5.*t9)./2.0+(m3.*t5.*t8)./2.0+(m4.*t5.*t7)./2.0+(m2.*t6.*t9)./2.0+(m3.*t6.*t8)./2.0+(m4.*t6.*t7)./2.0;
et2 = (m1.*t4.*t13)./2.0+(m2.*t4.*t12)./2.0+(m3.*t4.*t11)./2.0+(m4.*t4.*t10)./2.0+(m4.*t4.*t11)./2.0+(m1.*t6.*t13)./2.0+(m2.*t6.*t12)./2.0+(m3.*t6.*t11)./2.0+(m4.*t6.*t10)./2.0+(m4.*t6.*t11)./2.0+dth1.*dth2.*m2.*t9+dth1.*dth2.*m3.*t8+dth1.*dth2.*m4.*t7+dth1.*dth3.*m2.*t9+dth1.*dth3.*m3.*t8+dth1.*dth3.*m4.*t7+dth2.*dth3.*m2.*t9+dth2.*dth3.*m3.*t8+dth2.*dth3.*m4.*t7+dth1.*dth3.*m1.*t13+dth1.*dth3.*m2.*t12+dth1.*dth3.*m3.*t11+dth1.*dth3.*m4.*t10+dth1.*dth3.*m4.*t11+l_C_m4.*l_OA.*m4.*t4+l_C_m4.*l_OA.*m4.*t6+Ir.*N.*dth1.*dth2+Ir.*N.*dth1.*dth3+Ir.*N.*dth2.*dth3+dth1.*dth3.*l_C_m4.*l_OA.*m4.*2.0+l_AC.*l_C_m4.*m4.*t2.*t4+l_AC.*l_C_m4.*m4.*t2.*t6+l_AC.*l_OA.*m4.*t2.*t4+l_AC.*l_OA.*m4.*t2.*t6;
et3 = l_A_m3.*l_OA.*m3.*t2.*t4+l_A_m3.*l_OA.*m3.*t2.*t6+l_B_m2.*l_OB.*m2.*t2.*t4+l_B_m2.*l_OB.*m2.*t2.*t6+dth1.*dth2.*l_AC.*l_C_m4.*m4.*t2+dth1.*dth3.*l_AC.*l_C_m4.*m4.*t2.*2.0+dth2.*dth3.*l_AC.*l_C_m4.*m4.*t2+dth1.*dth2.*l_AC.*l_OA.*m4.*t2+dth1.*dth3.*l_AC.*l_OA.*m4.*t2.*2.0+dth2.*dth3.*l_AC.*l_OA.*m4.*t2+dth1.*dth2.*l_A_m3.*l_OA.*m3.*t2+dth1.*dth3.*l_A_m3.*l_OA.*m3.*t2.*2.0+dth2.*dth3.*l_A_m3.*l_OA.*m3.*t2+dth1.*dth2.*l_B_m2.*l_OB.*m2.*t2+dth1.*dth3.*l_B_m2.*l_OB.*m2.*t2.*2.0+dth2.*dth3.*l_B_m2.*l_OB.*m2.*t2;
E = et1+et2+et3;
end
