function keypoints = keypoints_ballerina(in1,in2)
%KEYPOINTS_BALLERINA
%    KEYPOINTS = KEYPOINTS_BALLERINA(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    14-Nov-2024 14:47:43

l_AC = in2(18,:);
l_DE = in2(19,:);
l_OA = in2(16,:);
l_OB = in2(17,:);
th1 = in1(1,:);
th2 = in1(2,:);
th3 = in1(3,:);
t2 = th1+th3;
t3 = cos(t2);
t4 = sin(t2);
t5 = t2+th2;
t6 = cos(t5);
t7 = sin(t5);
t8 = l_OA.*t3;
t9 = l_OB.*t3;
t10 = l_OA.*t4;
t11 = l_OB.*t4;
t12 = l_AC.*t6;
t13 = l_AC.*t7;
t14 = -t8;
t15 = -t9;
t16 = -t12;
keypoints = reshape([t10,t14,t11,t15,t10+t13,t14+t16,t11+t13,t15+t16,t11+t13+l_DE.*t4,t15+t16-l_DE.*t3],[2,5]);
end
